### ISSUE TITLE
Enhancing the working of Navbar

### ISSUE THREAD

**Issue by infinity1729** [Volley-Freak/gotLost#22]
Currently the navbar links of "Lost", "Found" and "About Us" don't work as expected. I would like to work on this issue to make those links redirect to the correct sections of page under Hacktoberfest 2021.

**Comment by Volley-Freak** [comment]
As this issue is already fixed you can work on some other issues like updating the redirect links of:
- [ ]  learn more in Got Lost section to about us
- [ ]  learn more in our mission section to about us
- [ ]  learn more in what we do section to about us
- [ ]  next buttons in our services section to lost and found pages
- [ ]  view more button in the recent return section to the gallery page(which we will add later)

After updating check each of them.
If you want to work on these issues do reply below @infinity1729

**Comment by infinity1729** [comment]
Sure, I'll work on them. Please assign them to me.
